site_name: Vertebrate Breed Ontology
theme: readthedocs
nav:
  - Getting started: index.md
  - VBO general information:
      - VBO general information: general/general.md
      - References for Livestock Breeds: general/references-livestock.md
      - References for Cat Breeds: general/references-cat.md
      - References for Dog Breeds: general/references-dog.md
  - VBO Developer Docs:
      - Components: VBO-editor-documents/components.md
      - Release process: VBO-editor-documents/release.md
      - Merging/obsoleting classes: VBO-editor-documents/merge_obsolete.md      
  - Cite: cite.md
  - History: history.md
  - How-to guides:
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Imports management: odk-workflows/UpdateImports.md
          - Managing the documentation: odk-workflows/ManageDocumentation.md
          - Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md
      - Contributing: contributing.md

